// Auto-generated by: supabase gen types typescript
// Run: pnpm supabase gen types typescript --project-id <id> > packages/auth/src/database.types.ts

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
